<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>playnite-reader</AssemblyName>
    <RootNamespace>Vgcm.PlayniteReader</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="4.1.4" />
  </ItemGroup>
</Project>
